name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Build and deploy
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'  # Replace with your target branch for deployment, if different
